---
# Log the output of a play
# Note: Set 'log_path=a4p.log' in ansible.cfg or run
#   'export ANSIBLE_LOG_PATH=a4p.log'. Run 'export -n \
#   ANSIBLE_LOG_PATH' to unset
# Usage:
# ANSIBLE_LOG_PATH=a4p.log ansible-playbook log_output.yml
# ANSIBLE_LOG_PATH=a4p.log ansible-playbook \
#   log_output.yml -v
- name: Log output
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Run the first task
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run a secret task
      ansible.builtin.debug:
        msg: "The super-secret squirrel password is 'qwerty'!"
      no_log: true

    - name: Run the last task
      ansible.builtin.debug:
        msg: "This is the last task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
