---
# Get the time it takes to run tasks
# Note: Set 'callbacks_enabled=ansible.posix.profile_tasks'
#   in ansible.cfg or run 'export \
#   ANSIBLE_CALLBACKS_ENABLED=ansible.posix.profile_tasks'
#   first. Run 'export -n ANSIBLE_CALLBACKS_ENABLED' to
#   unset
# Usage: ANSIBLE_CALLBACKS_ENABLED= \
#   ansible.posix.profile_tasks ansible-playbook \
#   profile_tasks.yml
- name: Profile tasks
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Run a fast task
      ansible.builtin.debug:
        msg: "This is a fast task."

    - name: Run a slower task
      ansible.builtin.pause:
        seconds: "3"
        prompt: "This is a slower task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
