---
# Check for multiple conditions in a task
# Usage: ansible-playbook combine_conditions.yml
- name: Combine conditions
  hosts: managed_node_1
  gather_facts: false
  vars:
    planet: "Mars"
    moons:
      - Phobos
      - Deimos
  tasks:
    - name: Show a message if all conditions are met
      ansible.builtin.debug:
        msg: "{{ 'Hi!' if planet == 'Mars' and 'Phobos'
          in moons }}"

    - name: Show a message if any condition is met
      ansible.builtin.debug:
        msg: "{{ 'Welcome to Mars!' if planet == 'Mars' or
          'Phobos' in moons }}"

    - name: Perform a task if all conditions are met
      ansible.builtin.debug:
        msg: "Both conditions met."
      when: planet == 'Mars' and 'Phobos' in moons

    - name: Skip a task if all conditions are not met
      ansible.builtin.debug:
        msg: "All conditions not met."
      when: planet == 'Earth' and 'Phobos' in moons

    - name: Perform a task if any condition is met
      ansible.builtin.debug:
        msg: "One or more conditions met."
      when: planet == 'Mars' or 'Phobos' in moons

    - name: Skip a task if a no conditions are met
      ansible.builtin.debug:
        msg: "No conditions met."
      when: planet == 'Earth' and 'Phobos' in moons
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
