---
# Get and display facts
# Usage: ansible-playbook get_facts.yml
- name: Get facts
  hosts: managed_node1, localhost
  gather_facts: false
  tasks:
    - name: Get facts
      ansible.builtin.setup:

    - name: Test
      ansible.builtin.debug:
        msg:
          - "{{ ansible_skip_tags }}"

    - name: Display facts gathered by default
      ansible.builtin.debug:
        msg: "{{ ansible_facts['ansible_default_ipv4']['address'] }}"
      when: >-
        ansible_facts['ansible_default_ipv4'] is defined and
        '192.168.68' in ansible_facts['ansible_default_ipv4']['address']

    - name: Display a fact gathered by default
      ansible.builtin.debug:
        msg: "{{ ansible_facts['default_ipv4']['address'] }}"
      when: >-
        ansible_facts['default_ipv4'] is defined and
        '192.168.68' in ansible_facts['default_ipv4']['address']
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
