---
# Break up long strings to improve readability
# Usage: ansible-playbook continue_lines.yml
- name: Continue lines
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Show a string using default flow
      ansible.builtin.debug:
        msg: "Happy Birthday to You, Happy Birthday to You, Happy Birthday, Happy Birthday, Happy Birthday to You!"

    - name: Break up a quoted string
      ansible.builtin.debug:
        msg: "Happy Birthday to You, Happy Birthday to You,
          Happy Birthday, Happy Birthday, Happy Birthday to
          You!"

    - name: Break up a string with a literal block scalar
      # A literal block scalar (|) preserves newlines
      # in a multiline string
      ansible.builtin.debug:
        msg: |
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Break up a string with a folded block scalar
      # A folded block scalar (>) collapses a multiline
      # string into a single line with a newline at the end
      ansible.builtin.debug:
        msg: >
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Chomp the last newline of a literal block scalar
      # A chomped literal block scalar (|) preserves
      # newlines, but removes the terminating newline
      ansible.builtin.debug:
        msg: |-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!

    - name: Chomp the last newline of a folded block scalar
      # A chomped folded block scalar (>) collapses
      # a multiline string into a single line
      # without a terminating newline
      ansible.builtin.debug:
        msg: >-
          Happy Birthday to You,
          Happy Birthday to You,
          Happy Birthday, Happy Birthday,
          Happy Birthday to You!
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
