---
# Group tasks using blocks
# Usage: ansible-playbook group_tasks.yml
- name: Group tasks
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Run a block of foo tasks
      block:
        - name: Run a foo task
          ansible.builtin.debug:
            msg: "This is a foo task."

        - name: Run another foo task
          ansible.builtin.debug:
            msg: "This is another foo task."

    - name: Run a block of bar tasks
      block:
        - name: Run a bar task
          ansible.builtin.debug:
            msg: "This is a bar task."

        - name: Run another bar task
          ansible.builtin.debug:
            msg: "This is another bar task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
