---
# Run multiple tasks in a play
# Usage: ansible-playbook run_multiple_tasks.yml
- name: Run multiple tasks
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Run a task
      ansible.builtin.debug:
        msg: "This is the first task."

    - name: Run another task
      ansible.builtin.debug:
        msg: "This is the second task."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
