%YAML 1.2
---
# Show a greeting using the debug module
# Usage: ansible-playbook say_hello.yml
- name: Say Hello
  hosts: all
  gather_facts: false
  tasks:
    - name: Show a greeting
      ansible.builtin.debug:
        msg: "Hello, World!"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
