[planets]
title = "This is a list of the major planets."

[[planets.planet]]
diameter = "4879"
hours_per_day = "4222.6"
name = "Mercury"
rings = "false"

[[planets.planet]]
diameter = "12104"
hours_per_day = "2802.0"
name = "Venus"
rings = "false"

[[planets.planet]]
diameter = "12756"
hours_per_day = "24.0"
name = "Earth"
rings = "false"

  [[planets.planet.moons]]
  moon = "Luna"

[[planets.planet]]
diameter = "6792"
hours_per_day = "24.7"
name = "Mars"
rings = "false"

  [[planets.planet.moons]]
  moon = "Phobos"

  [[planets.planet.moons]]
  moon = "Deimos"

[[planets.planet]]
diameter = "142984"
hours_per_day = "9.9"
name = "Jupiter"
rings = "true"

  [[planets.planet.moons]]
  moon = "Ganymede"

  [[planets.planet.moons]]
  moon = "Callisto"

  [[planets.planet.moons]]
  moon = "Europa"

  [[planets.planet.moons]]
  moon = "Io"

[[planets.planet]]
diameter = "120536"
hours_per_day = "10.7"
name = "Saturn"
rings = "true"

  [[planets.planet.moons]]
  moon = "Titan"

  [[planets.planet.moons]]
  moon = "Rhea"

  [[planets.planet.moons]]
  moon = "Iapetus"

  [[planets.planet.moons]]
  moon = "Dione"

  [[planets.planet.moons]]
  moon = "Tethys"

  [[planets.planet.moons]]
  moon = "Enceladus"

  [[planets.planet.moons]]
  moon = "Mimas"

[[planets.planet]]
diameter = "51118"
hours_per_day = "17.2"
name = "Uranus"
rings = "true"

  [[planets.planet.moons]]
  moon = "Titania"

  [[planets.planet.moons]]
  moon = "Oberon"

  [[planets.planet.moons]]
  moon = "Umbriel"

  [[planets.planet.moons]]
  moon = "Ariel"

  [[planets.planet.moons]]
  moon = "Miranda"

[[planets.planet]]
diameter = "49528"
hours_per_day = "16.1"
name = "Neptune"
rings = "true"

  [[planets.planet.moons]]
  moon = "Triton"
