---
# Set and show the value of a scalar variable
# Usage: ansible-playbook use_variables.yml
- name: Use variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and show a string variable
      vars:
        # Use quotation marks to explicitly declare strings
        planet: "Mercury"
      ansible.builtin.debug:
        msg: "{{ planet }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
