---
# Get and show special variables and facts
# Usage: ansible-playbook use_special_vars.yml
- name: Use special variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Show default magic variables
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show a magic variable
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: Scan the target node and gather facts
      ansible.builtin.setup:

    - name: Show magic variables and gathered facts
      # ansible_facts will only be populated for the target node
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show gathered facts only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Show a fact
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"

- name: Gather facts by default
  hosts: managed_node_1
  gather_facts: true
  tasks:
    # Results should be the same as the last three tasks
    # of the previous play
    - name: Show magic variables and gathered facts
      # ansible_facts will only be populated for the target node
      ansible.builtin.debug:
        msg: "{{ hostvars }}"

    - name: Show gathered facts only
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Show a fact
      ansible.builtin.debug:
        msg: "{{ ansible_facts['os_family'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
