---
# Set and show dictionaries of variables
# Usage: ansible-playbook use_dicts.yml
- name: Use dictionaries
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Set and show a dictionary
      vars:
        mars:
          planet: "Mars"
          diameter: 6792
          hours_per_day: 24.7
      ansible.builtin.debug:
        msg:
          - "{{ mars }}"
          - "{{ mars['planet'] }} is {{ mars.diameter }} km
            in diameter."
          - "One sol is {{ mars['hours_per_day'] }} Earth
            hours."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
