---
# Use variables from external files
# Usage: ansible-playbook include_vars.yml
- name: Include vars
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Include a YAML file in a play
      ansible.builtin.include_vars:
        dir: vars

    - name: Show the contents of the YAML file
      ansible.builtin.debug:
        msg: "{{ planets }}"

    - name: Access data from the YAML file
      ansible.builtin.debug:
        msg:
          - "Name: {{ planets['earth']['name'] }}"
          - "Moons: {{ planets['earth']['moons'] }}"

    - name: Include a JSON file in a play
      ansible.builtin.include_vars:
        file: files/planets_info.json
        name: from_json

    - name: Show the contents of the JSON file
      ansible.builtin.debug:
        msg: "{{ from_json }}"

    - name: Access data from the JSON file
      ansible.builtin.debug:
        msg:
          - "Name: {{ from_json.planets['mars']['name'] }}"
          - "Moons: {{ from_json.planets['mars']['moons'] }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
