---
# Replace content in files
# Usage: ansible-playbook replace_content.yml
- name: Add content
  ansible.builtin.import_playbook: add_content.yml

- name: Edit content
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Replace content in a file
      ansible.builtin.lineinfile:
        path: demo_dir/file_with_content.txt
        regexp: '(^H│\nH)ow.*$'
        line: "How are you doing?"

    - name: Read and show the contents of a file
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_file:
        - demo_dir/file_with_content.txt
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
