---
# Concatenate different types of variables
# Usage: ansible-playbook concat_variables.yml
- name: Concatenate variables
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Concatenate intergers
      vars:
        int1: 3
        int2: 8
      ansible.builtin.debug:
        msg:
          - "3 ~ 8: {{ int1 ~ int2 }}"
          - "[3, 8] │ join: {{ [int1, int2] │ join }}"
          # The plus sign adds! It does not concatenate
          - "3 + 8: {{ int1 + int2 }}"

    - name: Concatenate string variables
      vars:
        str1: "Mars"
        str2: " is a planet."
      ansible.builtin.debug:
        msg:
          - "{{ str1 ~ str2 }}"
          - "{{ [str1, str2] │ join }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
