---
# Format output using filters
# https://cplusplus.com/reference/cstdio/printf/
# Usage: ansible-playbook format_variables.yml
- name: Format variables
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Use printf style formatting
      vars:
        pi: 3.1415926536
        deg: 360
      ansible.builtin.debug:
        msg:
          - "{{ pi }}: {{ '%0.2f' % pi }}"
          - "{{ deg }}: {{ '%x' % deg }} (hex)"


    - name: Use format filter
      vars:
        pi: 3.1415926536
        deg: 360
      ansible.builtin.debug:
        msg:
          - "{{ pi }}: {{ '%0.2f' | format(pi) }}"
          - "{{ deg }}: {{ '%x' | format(deg) }} (hex)"

    - name: Use str.format() method
      vars:
        pi: 3.1415926536
        deg: 360
      ansible.builtin.debug:
        msg:
          - "{{ pi }}: {{ '{:.2f}'.format(pi) }}"
          - "{{ deg }}: {{ '{:#x}'.format(deg) }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
