---
# Ansible inventory using YAML format
# To view groups and nodes, use
# ansible-inventory --inventory inventory.yml --graph
all:
  children:
    control_nodes:
      hosts:
        control_node:
          ansible_connection: local
    managed_nodes:
      hosts:
        managed_node1:
        managed_node2:
      vars:
        ansible_connection: local
...
# code: language=yaml
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
